/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalvadosRouteImport } from './routes/salvados'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'

const SalvadosRoute = SalvadosRouteImport.update({
  id: '/salvados',
  path: '/salvados',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/salvados': typeof SalvadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/salvados': typeof SalvadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/salvados': typeof SalvadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mapa' | '/salvados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mapa' | '/salvados'
  id: '__root__' | '/' | '/mapa' | '/salvados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  SalvadosRoute: typeof SalvadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salvados': {
      id: '/salvados'
      path: '/salvados'
      fullPath: '/salvados'
      preLoaderRoute: typeof SalvadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  SalvadosRoute: SalvadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
